### ISSUE TITLE
Allow to change config path

### ISSUE THREAD

**Issue by P4sca1** [northwood-studios/LocalAdmin-V2#18]
With the latest release, the server crashes when it cant create the config directory.

```
11.01. - 10:28:34 FATAL ERROR: Can't create config directory.
11.01. - 10:28:34 Path: /SCP Secret Laboratory/config/7778/
11.01. - 10:28:34 Exception: Read-only file system
```

I am running the server inside a secured environment where only the home directory of the user running the server is writeable. Therefore I need to change the config directory. A new startup argument for this purpose would be great.

**Comment by zabszk** [comment]
LocalAdmin uses home directory. In your case your environment has redirected the user home directory to the root directory (probably HOME env var is not set). We can add such parameter, but making sure to set the HOME env (which is normally set) should fix the issue.

**Comment by P4sca1** [comment]
I will try setting the HOME env var and let you know if it worked.

**Comment by zabszk** [comment]
We have just released a new version of LocalAdmin adding `--config` startup argument. You can use it (eg. `--config /home/username/.config/SCP Secret Laboratory/config/7778/localadmin_config.txt`), but fixing HOME env should be better (will cause less issues in the future).
