### ISSUE TITLE
after exception, the players could not join

### ISSUE THREAD

**Issue by agent188** [northwood-studios/LocalAdmin-V2#22]
![изображение](https://user-images.githubusercontent.com/41228098/108961250-1e3ee400-7688-11eb-922a-cdf4baaf57ac.png)
The server continued to work, but players could not connect to it

**Comment by agent188** [comment]
![изображение](https://user-images.githubusercontent.com/41228098/109109039-b18a1f00-7745-11eb-8a1a-806d0bda7425.png)
the problem is related to opening the port

**Comment by zabszk** [comment]
Are you sure it's related to this error? Are there any other errors from SCP:SL itself?

Can you check if the server is listening on any IP address `netstat -au | grep 7779` ?
