### ISSUE TITLE
[SUGGESTION] Have the list command have the proper "formatting"

### ISSUE THREAD

**Issue by EsserGaming** [northwood-studios/LocalAdmin-V2#30]
![image](https://user-images.githubusercontent.com/36900138/136645746-fa487d4a-bac2-4cbd-814d-344e55db4097.png)
What I mean by "formatting" is the image above, it's not a big deal but it would be nice if it was fixed.

I hope this is enough information, if not I will happily give more.

**Comment by zabszk** [comment]
Resolved in #31.
