### ISSUE TITLE
How to bind the server ip?

### ISSUE THREAD

**Issue by stefanofabi** [northwood-studios/LocalAdmin-V2#35]
Hello, I have two IPs on my machine, I am already running an SCP server on one IP and I wanted to run another SCP server with the default port on the same machine with another IP.

The problem is that even though I specify the server_ip it still takes me the main IP of the machine.

Any way to specify the ip in the launch parameters?

Thanks!

**Comment by zabszk** [comment]
Hi,

You need to change `ipv4_bind_ip` and `ipv6_bind_ip` values in the config. They are responsible for changing the binding IP address. The value of `server_ip` only specifies the address that is visible on the in-game servers list (if the server is verified and public).

Btw. this is the repository of Local Admin (a tool used to manage SCP:SL dedicated servers), not the SCP:SL game itself. If you have any further issues with the game, please contact our tech support on our Discord server (https://discord.gg/scpsl).
