### ISSUE TITLE
[Bug] Config folder with port 0

### ISSUE THREAD

**Issue by SrLicht** [northwood-studios/LocalAdmin-V2#57]
No matter how many times I do this this folder is not deleted, it happens since 11.0
![image](https://user-images.githubusercontent.com/36207738/211636540-722fd474-8d98-4301-b1d2-0b132deed0e0.png)

**Comment by zabszk** [comment]
That's a SCP:SL bug, not LA bug, so it should be reported using the bug reporting form. I will try to fix it anyway of course.

**Comment by zabszk** [comment]
The bug has been fixed in the base game and will be included in the next release.
