### ISSUE TITLE
[BUG] Help command doesn't show the arguments on Pterodactyl

### ISSUE THREAD

**Issue by EsserGaming** [northwood-studios/LocalAdmin-V2#59]
### Windows/CLI
Shows all the information correctly.
![image](https://github.com/northwood-studios/LocalAdmin-V2/assets/36900138/95f215b6-97e6-4554-ad72-abdaf0152b56)

### Pterodactyl
As you can see, there is nothing showing in the blank space.
![image](https://github.com/northwood-studios/LocalAdmin-V2/assets/36900138/b1f64dde-cea3-48bf-893b-401879f2ec2a)

**Comment by zabszk** [comment]
I just checked it. I couldn't see it either, but if you select that empty space, copy that and paste into notepad the text is there. I don't know why pterodactyl doesn't show that text, but LocalAdmin is printing it. That looks like a pterodactyl issue to me.

**Comment by EsserGaming** [comment]
> I just checked it. I couldn't see it either, but if you select that empty space, copy that and paste into notepad the text is there. I don't know why pterodactyl doesn't show that text, but LocalAdmin is printing it. That looks like a pterodactyl issue to me.

I'm not sure how I'd get around it then. Should I make an issue on the panel?

**Comment by zabszk** [comment]
> I'm not sure how I'd get around it then. Should I make an issue on the panel?

Yes. I would say that you should report the issue there, because for some reason Pterodactyl doesn't show that text. My guess is that it's related to the color of that text.

**Comment by EsserGaming** [comment]
> I just checked it. I couldn't see it either, but if you select that empty space, copy that and paste into notepad the text is there. I don't know why pterodactyl doesn't show that text, but LocalAdmin is printing it. That looks like a pterodactyl issue to me.

Coming back to this, I was thinking if changing the color of the text would fix the issue?

**Comment by ALEXWARELLC** [comment]
Why did I receive an email about this? lol
