### ISSUE TITLE
Disable STDOUT Logs

### ISSUE THREAD

**Issue by ALEXWARELLC** [northwood-studios/LocalAdmin-V2#91]
Is there a feature or flag which disables standard output or is that not a thing?

Thanks.

**Comment by zabszk** [comment]
Hi,

I assume you are asking about stdout of SCP:SL (not LA iteself) being either displayed or logged by the LA. If so, both are configurable separately. You can change the values by editing the LA config file or running the config wizard (`--reconfigure` argument).

**Comment by ALEXWARELLC** [comment]
Ok, all good, thanks.
