### ISSUE TITLE
Restarts limit exceeded

### ISSUE THREAD

**Issue by AndreaPenna01** [northwood-studios/LocalAdmin-V2#94]
When I try to start the Server it gives me this error: _Restarts limit exceeded_. Can someone help me please? 

![image](https://github.com/user-attachments/assets/1def95a0-3678-4261-b9c5-771e2dbd3cf5)

**Comment by zabszk** [comment]
Hi,

It looks like SCP:SL server is crashing during startup. Can you enable LocalAdmin logs (both console output and stdin/stderr) in LocalAdmin config, try again and then check the generated log files?

It's very likely a game issue, not LocalAdmin issue. If that's the case, please contact SCP:SL technical support.
